
version: '3.9'

services:

  container_starter_gradle:
    image: container_starter_gradle:latest
    build:
      dockerfile: gradle.dockerfile
    ports:
      - "9910:9090"

  container_starter_jpackage:
    image: container_starter_jpackage:latest
    build:
      dockerfile: jpackage.dockerfile
    ports:
      - "9920:9090"

  container_starter_native:
    image: container_starter_native:latest
    build:
      dockerfile: native.dockerfile
    ports:
      - "9930:9090"
